package cloud.xcan.angus.core.repo.domain;


public interface Constants {

  // 通用限制
  int MAX_NAME_LENGTH = 255;
  int MAX_DESC_LENGTH = 2000;
  int MAX_URL_LENGTH = 500;
  int MAX_EMAIL_LENGTH = 255;
  int MAX_TOKEN_LENGTH = 255;

  // 仓库相关
  int MAX_REPOSITORY_NAME_LENGTH = 255;
  int MAX_REPOSITORY_DESC_LENGTH = 2000;
  int MAX_REPOSITORY_URL_LENGTH = 500;

  // 团队相关
  int MAX_INVITATION_MESSAGE_LENGTH = 1000;
  int INVITATION_EXPIRE_DAYS = 7;

  // 用户相关
  int MAX_DEPARTMENT_LENGTH = 255;
  int MAX_AVATAR_SIZE = 2 * 1024 * 1024; // 2MB

  // API Token相关
  int MAX_API_TOKEN_NAME_LENGTH = 255;
  int MAX_API_TOKEN_PER_USER = 20;

  // 系统设置相关
  int MAX_SETTING_KEY_LENGTH = 255;
  int MAX_LICENSE_KEY_LENGTH = 10000;

  // 制品相关
  int MAX_ARTIFACT_NAME_LENGTH = 255;
  int MAX_ARTIFACT_PATH_LENGTH = 1000;
  int MAX_ARTIFACT_VERSION_LENGTH = 100;
  int MAX_ARTIFACT_CHECKSUM_LENGTH = 128;
  int MAX_ARTIFACT_LICENSE_LENGTH = 255;

  // 上传相关
  int MAX_UPLOAD_FILE_NAME_LENGTH = 255;
  long MAX_UPLOAD_CHUNK_SIZE = 100 * 1024 * 1024; // 100MB
  int UPLOAD_TOKEN_EXPIRE_HOURS = 24;

  // 访问控制相关
  int MAX_ACCESS_RULE_NAME_LENGTH = 255;
  int MAX_ACCESS_TOKEN_NAME_LENGTH = 255;
  int MAX_IP_WHITELIST_SIZE = 100;

  // Webhook相关
  int MAX_WEBHOOK_NAME_LENGTH = 255;
  int MAX_WEBHOOK_URL_LENGTH = 500;
  int MAX_WEBHOOK_SECRET_LENGTH = 255;
  int WEBHOOK_TIMEOUT_SECONDS = 30;
}
