<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>cloud.xcan.angus</groupId>
    <artifactId>xcan-angusrepo.service</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>xcan-angusrepo.core</artifactId>
  <name>AngusRepo :: Core</name>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-infra.core</artifactId>
    </dependency>

    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-infra.lettucex</artifactId>
    </dependency>

    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-infra.datasource</artifactId>
    </dependency>

    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-infra.l2cache-core</artifactId>
    </dependency>

    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-plugin.spring</artifactId>
    </dependency>

    <!-- Note: Cannot move to the front, which will cause OAS failure in Angus -->
    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-angusrepo.api</artifactId>
    </dependency>

    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-angusgm.api</artifactId>
    </dependency>

    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-angusstorage.api</artifactId>
    </dependency>

    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-angusess.api</artifactId>
    </dependency>

    <dependency>
      <groupId>cloud.xcan.angus</groupId>
      <artifactId>xcan-angusexpense.api</artifactId>
    </dependency>

    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-text</artifactId>
    </dependency>

    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
